shopt -s globstar

get_credit() {
	{
		while IFS= read -r line; do
			name=${line%%=*}
			value=$(echo ${line#*=} | tr -d '"')

			case $name in
				"user.dublincore.title")
					title=$value
					;;
				"user.dublincore.creator")
					creator=$value
					;;
				"user.dublincore.source")
					src=$value
					;;
				"user.dublincore.rights")
					rights=$value
					;;
				"user.modified")
					modified=$value
					;;
			esac
		done
	} < <(getfattr --match=user -d "$1" | head -n -1 | tail -n +2)

	if [[ -z "$title" || -z "$creator" || -z "$src" || -z "$rights" ]]; then
		return
	fi

	credit="$title|By $creator|From $src|Released under $rights"
	if [ "$modified" == "true" ]; then
		credit="$credit|Modified from the original"
	fi
	
	echo $credit | jq -R
}

# Generate final in-game credits (only shows the asset name, not file path and also includes third-party software licenses).

credits=gui/credits/credits.json

rm $credits

echo "[" >> $credits
echo [\"Barrel of Laughs\", \"A game by Leroy Hopson\"] | jq >> $credits
echo "," >> $credits
echo [\"Character Voices\", \"Generated by 15.ai \(https://15.ai\)\"] | jq >> $credits
for asset in **/assets/final/**; do
	credit=$(get_credit "$asset")
	if [[ "$credit" == "" ]]; then
		continue
	fi
	echo [$credit]
done | awk NF | sort | uniq | sed 's/^/,/' | sed 's/|/","/g' >> $credits
for license in thirdparty/**/LICENSE*; do
	echo ,[\"$(basename $(dirname $license))\",
	cat $license | jq -Rs | sed 's/\\n/","/g'
	echo ]
done >> $credits
echo , >> $credits
echo [\"License\", \"The Barrel of Laughs code is free software\;\", \"you can redistribute it and/or modify it under the terms of the GNU\", \"General Public License as published by the Free Software Foundation\;\", \"either version 3 of the License, or \(at your option\) any later version.\"] | jq >> $credits
echo "]" >> $credits
